parameters:
  - name: hdf5tag
    default: hdf5-1_10_7
  - name: extraflags
    default: ''
  - name: gui
    default: true
  - name: threading
    default: true

steps:
  - bash: |
      set -ex
      # -- General
      sudo apt-get update -q
      sudo apt-get install antlr4 ninja-build python3-setuptools uuid uuid-dev
      # -- Qt
      sudo apt-get install qtbase5-dev libqt5svg5-dev qt5-image-formats-plugins -y
    displayName: 'Install Prerequisites'
  - bash: |
      wget https://github.com/disorderedmaterials/HDF5/releases/download/${{ parameters.hdf5tag }}/${{ parameters.hdf5tag }}-linux.zip
      unzip ${{ parameters.hdf5tag }}-linux.zip
    displayName: 'Download HDF5 Artifacts'
  - bash: |
      set -ex
      HDF5_DIR="$(pwd)/${{ parameters.hdf5tag }}"
      # Building
      mkdir build
      cd build
      cmake ../ -G Ninja ${{ parameters.extraflags }} -DLOCAL_STATIC_HDF5:bool=true -DHDF5_DIR:path=${HDF5_DIR}
      ninja
    displayName: 'Build'