parameters:
  - name: hdf5tag
    default: hdf5-1_10_7
  - name: extraflags
    default: ''
  - name: ppa
    default: 'beineri/opt-qt-5.15.2-focal'
  - name: qtver
    default: 515
  - name: gui
    default: true
  - name: threading
    default: true

steps:
  - bash: |
      set -ex
      brew update-reset
      brew install ninja
      brew install qt5
    displayName: 'Install Prerequisites'
  - bash: |
      wget https://github.com/disorderedmaterials/HDF5/releases/download/${{ parameters.hdf5tag }}/${{ parameters.hdf5tag }}-osx.zip
      unzip ${{ parameters.hdf5tag }}-osx.zip
      ls
    displayName: 'Download HDF5 Artifacts'
  - bash: |
      set -ex
      HDF5_DIR="$(pwd)/${{ parameters.hdf5tag }}"
      # Managing packages
      QT_INSTALL_DIR=/usr/local/Cellar/qt@5
      QTVER=`ls -d ${QT_INSTALL_DIR}/* | sed "s/.*\(5\.[0-9][0-9]\.[0-9]\)/\1/g"`
      export Qt5_DIR=${QT_INSTALL_DIR}/$QTVER/lib/cmake/Qt5
      export Qt5Core_DIR=${QT_INSTALL_DIR}/$QTVER/lib/cmake/Qt5Core
      export Qt5Widgets_DIR=${QT_INSTALL_DIR}/$QTVER/lib/cmake/Qt5Widgets
      export Qt5Network_DIR=${QT_INSTALL_DIR}/$QTVER/lib/cmake/Qt5Network
      export Qt5PrintSupport_DIR=${QT_INSTALL_DIR}/$QTVER/lib/cmake/Qt5PrintSupport
      export Qt5Gui_DIR=${QT_INSTALL_DIR}/$QTVER/lib/cmake/Qt5Gui
      export Qt5Svg_DIR=${QT_INSTALL_DIR}/$QTVER/lib/cmake/Qt5Svg
      Qt5_ROOT=${QT_INSTALL_DIR}/${QTVER}
      # Building
      mkdir build
      cd build
      cmake ../ -G Ninja -DCMAKE_Fortran_COMPILER:string="gfortran-11" -DLOCAL_STATIC_HDF5:bool=True -DHDF5_DIR:path=${HDF5_DIR} ${{ parameters.extraflags }}
      ninja
    displayName: 'Build'